version: "3.7"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

  johnny_checkup:
    build:
      context: .
    restart: always
    environment:
      - LOG_LEVEL=info
      # LOG_LOCATION=/some/file
      - HTTP_USER_AGENT
      - HTTP_USERS

volumes:
  caddy_data:
